### ISSUE TITLE
LightFM rows and columns order

### ISSUE THREAD

**Issue by jrzaurin** [tdeboissiere/Kaggle#1]
Hi Thibault. 

I was about to use lightFM and I found this very nice repo from you. I am wondering something related to the building of the training matrix, the user and the item feature matrix. I was wondering if the rows and columns have to be passed in a specific order? I am assuming is the case, but in your building, I can't see where you do that.

I understand `Mui_train` is  a `COO` sparse matrix and `uf` and `itrf` are `CSR`.  When you pass these to `model.fit_partial`, how does the method understand which rows and columns in `Mui_train` belong to which user and item in `uf` and `itrf`?

Thanks!

Javier

**Comment by tdeboissiere** [comment]
Hi Javier, did you have a look at this notebook (https://github.com/tdeboissiere/Kaggle/blob/master/Ponpare/ponpare_lightfm.ipynb) ? I wrote this for a more detailed walkthrough.

If that's not enough, I'll try to refresh my memory.
